import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { AiOutlineUser } from 'react-icons/ai'

import { useForm } from 'react-hook-form'
import { useRouter } from 'next/router'
import { useState } from 'react'


import { yupResolver } from '@hookform/resolvers/yup'
import * as yup from 'yup'


const schema = yup.object({
  name: yup.string("O nome deverá conter somente letras").required("O nome é obrigatório"),
  email: yup.string().email("Digite um email válido").required("O email é obrigatório"),
  password: yup.string().required("A senha é obrigatória").min(6, "A senha deve ter pelos menos 6 digitos"),
  confirmPassword: yup.string().required("Comfirmar senha é obrigatório").oneOf([yup.ref("password")], " As senhas devem ser iguais"),
}).required()

export default function Home() {


  const router = useRouter();

  const { handleSubmit, register, formState: { errors }, } = useForm({
    resolver: yupResolver(schema)
  })


  function handleRegistration(e) {
    router.push(`/Success?name=${e.name}`);
  }


  return (
    <div className={styles.page}>
      <Head>
        <title>Form - Use Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.form_container}>
          <div className={styles.title_form}>
            <AiOutlineUser />
            <h1>Cadastro</h1>
          </div>
          <form onSubmit={handleSubmit(handleRegistration)}>
            <label>
              Nome
              <input
                {...register('name')}
                type='text'
                placeholder='Digite seu nome'
              />
              <span>{errors.name?.message}</span>
            </label>

            <label>
              Email
              <input
                {...register('email')}
                type='text'
                placeholder='Digite seu email'
              />
              <span>{errors.email?.message}</span>
            </label>

            <label>
              Senha
              <input
                {...register('password')}
                type='password'
                placeholder='Digite sua senha'
              />
              <span>{errors.password?.message}</span>
            </label>

            <label>
              Confirme sua Senha
              <input
                {...register('confirmPassword')}
                type='password'
                placeholder='Digite sua senha'
              />
              <span>{errors.confirmPassword?.message}</span>
            </label>
            <div className={styles.btn}>
              <button type='submit'>Cadastrar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}
